app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField, SelectField
from wtforms.validators import Required, Length, Email, Regexp
from ..models import User, Role
from flask_pagedown.fields import PageDownField

class EditProfileForm(FlaskForm):
    name = StringField('Real name', validators=[Length(0, 64)])
    location = StringField('Location', validators=[Length(0, 64)])
    about_me = TextAreaField('About me')
    submit = SubmitField('Submit')

class EditProfileAdminForm(FlaskForm):
    email = StringField('Email', validators=[Required(), Length(1, 64), Email()])
    username = StringField('Username', validators=[
        Required(), Length(1, 64), Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0, 'Usernames must \
                                          have only letters, numbers, dots or underscores \
                                          and must begin with letters.')])
    confirmed = BooleanField('confirmed')
    role = SelectField('Role', coerce=int)
    name = StringField('Real name', validators=[Length(0, 64)])
    location = StringField('Location', validators=[Length(0, 64)])
    about_me = TextAreaField('About me')
    submit = SubmitField('Submit')

    def __init__(self, user, *args, **kwargs):
        super(EditProfileAdminForm, self).__init__(*args, **kwargs)

        # to implement `SelectField` member. 
        self.role.choices = [(role.id, role.name) \
                             for role in Role.query.order_by(Role.name).all()]
        
        # in order to implement custome validate methods, we should take user object 
        # as a member variable.
        self.user = user

    def validate_email(self, field):
        if field.data != self.user.email and \
                User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already registered.')
 
    def validate_username(self, field):
        if field.data != self.user.username and \
                User.query.filter_by(username=field.data).first():
            raise ValidationError('Username already in use.')

class PostForm(FlaskForm):
    body = StringField("What's on your mind?", validators=[Required()])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    body = StringField('Comment here', validators=[Required()])
    submit = SubmitField('Submit')

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views
from .. models import Permission

@main.app_context_processor
def inject_permission():
    '''Permissions may also need to be checked from templates, so the `Permission` class
    with all the bit constants needs to be accessible to them. To avoid having to add a 
    template argument in every `render_template` call, a `context processor` can be used.
    Context processors make variables globally available to all templates.
    '''
    return dict(Permission=Permission)

app/main/views.py
from flask import render_template, redirect, flash, url_for, request, current_app
from flask_login import login_required, current_user
from flask_sqlalchemy import get_debug_queries

from . import main
from ..models import User, db, Role, Permission, Post, Follow, Comment
from ..decorators import permission_required, admin_required
from .forms import EditProfileForm, EditProfileAdminForm, PostForm, CommentForm

@main.after_app_request
def after_request(response):
    '''Log queries that are slower than a configured threshold.'''
    for query in get_debug_queries():
        if query.duration >= current_app.config['FLASKY_SLOW_DB_QUERY_TIME']:
            current_app.logger.warning(
                'Slow query: %s\nParameters: %s\nDuration: %fs\nContext: %s\n' %
                    (query.statement, query.parameters, query.duration, query.context))
    return response

@main.route('/', methods=['GET', 'POST'])
@main.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    form = PostForm()
    if (current_user.can(Permission.WRITE_ARTICLES) and 
            form.validate_on_submit()):
        # `current_user` is a LocalProxy() instance, it is readlly a thin
        # wrapper that contains the actual user object inside. If you want to 
        # get the real user object, you need to call `_get_current_object()`
        post = Post(body=form.body.data, 
                    author=current_user._get_current_object())
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('main.index'))

    # The page number to render is obrained from the request's query string, which
    # is available as `request.args`. When an explicit page isn't given, a default
    # page of 1(the first page) is used. The `type=int` argument ensures that if the 
    # argument cannot be converted to an integer, the default value is returned.
    page = request.args.get('page', 1, type=int)
    pagination = (current_user.followed_posts.order_by(Post.timestamp.desc()).
        paginate(page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'], 
                 error_out=False))
    posts = pagination.items
    return render_template('main/index.html', form=form, 
                           posts=posts, pagination=pagination)

@main.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('User %s is not found.' % username)
        abort(404)
    page = request.args.get('page', 1, type=int)
    pagination = (Post.query.filter_by(author=user).order_by(Post.timestamp.desc()).
        paginate(page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'], 
                 error_out=False))
    posts = pagination.items
    return render_template('main/user.html', user=user, 
                            posts=posts, pagination=pagination)

@main.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.about_me = form.about_me.data
        db.session.add(current_user)
        flash('Your profile has been updated.')
        return redirect(url_for('.user', username=current_user.username))
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.about_me.data = current_user.about_me
    return render_template('main/edit_profile.html', form=form)

@main.route('/edit-profile/<int:id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_profile_admin(id):
    user = User.query.get_or_404(id)
    form = EditProfileAdminForm(user=user)
    if form.validate_on_submit():
        user.email = form.email.data
        user.username = form.username.data
        user.confirmed = form.confirmed.data
        user.role = Role.query.get(form.role.data)
        user.name = form.name.data
        user.location = form.location.data
        user.about_me = form.about_me.data
        db.session.add(user)
        db.session.commit()
        flash('The profile has been updated.')
        return redirect(url_for('main.user', username=user.username))
    form.email.data = user.email
    form.username.data = user.username
    form.confirmed.data = user.confirmed
    form.role.data = user.role_name
    form.name.data = user.name
    form.location.data = user.location
    form.about_me.data = user.about_me
    return render_template('main/edit_profile.html', form=form, user=user)

@main.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    post = Post.query.get_or_404(id)
    if current_user != post.author and \
            not current_user.can(Permission.ADMINISTER):
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.body = form.body.data
        db.session.add(post)
        db.session.commit()
        flash('The post has been updated')
        return redirect(url_for('main.post', id=post.id))
    form.body.data = post.body
    return render_template('main/edit_post.html', form=form)

@main.route('/post/<int:id>', methods=['GET', 'POST'])
def post(id):
    post = Post.query.get_or_404(id)
    if current_user.can(Permission.COMMENT):
        form = CommentForm()
        if form.validate_on_submit():
                comment = Comment(body=form.body.data, post=post, 
                    author=current_user._get_current_object())
                db.session.add(comment)
                db.session.commit()
                return redirect(url_for('main.post', id=post.id))
    page = request.args.get('page', 1, type=int)
    '''if page == -1:
        page = (post.comments.count() - 1) / current_app \
            .config['FLASKY_COMMENTS_PER_PAGE']'''
    pagination = post.comments.order_by(Comment.timestamp.desc()).paginate(page, 
        per_page=current_app.config['FLASKY_COMMENTS_PER_PAGE'], error_out=False)
    comments = pagination.items
    return render_template('main/post.html', posts=[post], 
        form=form, comments=comments, pagination=pagination)

@main.route('/follow/<username>')
@login_required
@permission_required(Permission.FOLLOW)
def follow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Not found user %s' % username)
        return redirect(url_for('main.index'))
    if current_user.is_following(user):
        flash('You are already following this user.')
        return redirect(url_for('main.user', username=username))
    current_user.follow(user)
    flash('You are now following %s.' % username)
    return redirect(url_for('main.user', username=username))

@main.route('/unfollow/<username>')
@login_required
@permission_required(Permission.FOLLOW)
def unfollow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Not found user %s' % username)
        return redirect(url_for('main.index'))
    if not current_user.is_following(user):
        flash('You are not following %s.' % username)
        return redirect(url_for('main.user', username=username))
    current_user.unfollow(user)
    flash('You have unfollowed %s.' % username)
    return redirect(url_for('main.user', username=username))

@main.route('/followers/<username>')
def followers(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Not found user %s' % username)
        return redirect(url_for('main.index'))
    page = request.args.get('page', 1, type=int)
    pagination = user.followers.order_by(Follow.timestamp.desc()).paginate( \
        page, per_page=current_app.config['FLASKY_FOLLOWERS_PER_PAGE'], error_out=False)
    follows = [{'user': item.follower, 'timestamp': item.timestamp}
                 for item in pagination.items]
    return render_template('main/followers.html', follows=follows, user=user,
                           endpoint='main.followers', pagination=pagination, 
                           title='Followers of')

@main.route('/followed_by/<username>')
def followed_by(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Not found user %s' % username)
        return redirect(url_for('main.index'))
    page = request.args.get('page', 1, type=int)
    pagination = user.followed.order_by(Follow.timestamp.desc()).paginate(page, 
        per_page=current_app.config['FLASKY_FOLLOWERS_PER_PAGE'], error_out=False)
    follows = [{'user': item.followed, 'timestamp': item.timestamp}
                 for item in pagination.items]
    return render_template('main/followers.html', follows=follows, user=user,
                           endpoint='main.followed_by', pagination=pagination, 
                           title='Followed by')

@main.route('/moderate')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate():
    page = request.args.get('page', 1, type=int)
    pagination = Comment.query.order_by(Comment.timestamp.desc()).paginate(
        page, per_page=current_app.config['FLASKY_COMMENTS_PER_PAGE'],
        error_out=False)
    comments = pagination.items
    return render_template('main/moderate.html', comments=comments,
                           pagination=pagination, page=page)

@main.route('/moderate/enable/<int:id>')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate_enable(id):
    comment = Comment.query.get_or_404(id)
    comment.disabled = False
    db.session.add(comment)
    db.session.commit()
    return redirect(url_for('main.moderate', 
                            page=request.args.get('get', 1, type=int)))

@main.route('/moderate/disable/<int:id>')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate_disable(id):
    comment = Comment.query.get_or_404(id)
    comment.disabled = True
    db.session.add(comment)

app/templates/main/_comments.html
<ul class='comments'>
    {% for comment in comments %}
    <li class='comment'>
        <div class='comment-thumbnail'>
            <a href="{{ url_for('main.user', username=comment.author.username) }}">
                <img class='img-rounded profile-thumbnail' src='{{ comment.author.gravatar(size=40) }}'>
            </a>
        </div>

        <div class='comment-content'>
            <div class='comment-date'>{{ moment(comment.timestamp).fromNow() }}</div>
            <div class='comment-author'>
                <a href="{{ url_for('main.user', username=comment.author.username) }}">
                    {{ comment.author.username }}
                </a>
            </div>
            <div class='comment-body'>
                {% if comment.disabled %}
                <p><i>The comment has been disabled.</i></p>
                {% endif %}
                {% if moderate or not comment.disabled %}
                    {% if comment.body_html %}
                        {{ comment.body_html | safe }}
                    {% else %}
                        {{ comment.body }}
                    {% endif %}
                {% endif %}
            </div>
            {% if moderate %}
                <br>
                {% if comment.disabled %}
                <a class='btn btn-default btn-xs' href="{{ url_for('main.moderate_enable', id=comment.id, page=page) }}">
                    Enable
                </a>
                {% else %}
                <a class='btn btn-danger btn-xs' href="{{ url_for('main.moderate_disable', id=comment.id, page=page) }}">
                    Disable
                </a>
                {% endif %}
            {% endif %}
        </div>
    </li>
    {% endfor %}
</ul>

app/templates/main/_macros.html
{% macro pagination_widget(pagination, endpoint, fragment='') %}
<ul class='pagination'>

    <!-- A 'previous page' link -->
    <li{% if not pagination.has_prev %} class='disabled'{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint,
            page=pagination.prev_num, **kwargs) }}{{ fragment }}
            {% else %}#{% endif %}">
            &laquo;
        </a>
    </li>

    <!-- links to the all pages with an explicit page number, the page
    currently displayed is highlighted using the `active CSS` class,
    `Gaps` in the sequence of pages are rendered with the ellipsis character
    -->
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p==pagination.page %}
            <li class='activate'>
                <a href="{{ url_for(endpoint, page=p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% else %}
             <li>
                <a href="{{ url_for(endpoint, page=p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class='disabled'><a href='#'>&hellip;</a></li>
        {% endif %}
    {% endfor %}

    <!-- A 'next page' link -->
    <li{% if not pagination.has_next %} class='disabled'{% endif %}>
        <a href='{% if pagination.has_next %}{{ url_for(endpoint,
            page=pagination.page+1, **kwargs) }}{{ fragment }}{% else %}#{% endif %}'>
            &raquo;
        </a>
    </li>

</ul>
{% endmacro %}

app/templates/main/_posts.html
<ul class='posts'>
    {% for post in posts %}
    <li class='post'>
        <div class='post-thumbnail'>
            <a href="{{ url_for('main.user', username=post.author.username) }}">
                <img class='img-rounded profile-thumbnail' src='{{ post.author.gravatar(size=40) }}'>
            </a>
        </div>

        <div class='post-content'>
            <div class='post-date'>{{ moment(post.timestamp).fromNow() }}</div>
            <div class='post-author'>
                <a href="{{ url_for('main.user', username=post.author.username) }}">
                    {{ post.author.username }}
                </a>
            </div>
            <div class='post-body'>
                {% if post.body_html %}
                    {{ post.body_html | safe }}
                {% else %}
                    {{ post.body }}
                {% endif %}
            </div>
        </div>

        <div class='post-footer'>
            {% if current_user == post.author %}
            <a href="{{ url_for('main.edit', id=post.id) }}">
                <span class='label label-primary'>Edit</span>
            </a>
            {% elif current_user.is_administrator() %}
            <a href="{{ url_for('main.edit', id=post.id) }}">
                <span class='label label-danger'>Edit [Admin]</span>
            </a>
            {% endif %}
            <a href="{{ url_for('main.post', id=post.id) }}">
                <span class='label label-default'>Permalink</span>
            </a>
            <a href="{{ url_for('main.post', id=post.id) }}#comments">
                <span class='label label-default'>{{ post.comments.count() }} Comments</span>
            </a>
        </div>
    </li>
    {% endfor %}
</ul>

app/templates/main/edit_post.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}Flasky - Edit Post{% endblock %}

{% block page_content %}
<div class='page-header'>
    <h1>Edit Post</h1>
</div>
<div>
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

app/templates/main/edit_profile.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}Flasky - Edit Profile{% endblock %}

{% block page_content %}
<div class='page-header'>
    <h1>Edit Profile</h1>
</div>
<div class='col-md-4'>
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/main/followers.html
{% extends 'base.html' %}
{% import 'main/_macros.html' as macros %}

{% block title %}Flask - {{ title }} {{ user.username }}{% endblock %}

{% block page_content %}
<div class='page-header'>
    <h1>{{ title }} {{ user.username }}</h1>
</div>

<table class='table table-hover followers'>
    <thread>
        <tr>
            <th>User</th>
            <th>Since</th>
        </tr>
    </thread>
    {% for follow in follows %}
    {% if follow.user != user %}
    <tr>
        <td>
            <a href="{{ url_for('main.user', username=follow.user.username) }}">
                <img class='img-rounded' src="{{ follow.user.gravatar(size=32) }}">
                {{ follow.user.username }}
            </a>
        </td>
    </tr>
    {% endif %}
    {% endfor %}
</table>

<div class='pagination'>
    {{ macros.pagination_widget(pagination, 'main.user', username=user.username) }}
</div>
{% endblock %}

app/templates/main/index.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% import 'main/_macros.html' as macros %}

{% block title %}Flasky{% endblock %}

{% block page_content %}
<div class='page-header'>
    <h1>Hello, 
    {% if current_user.is_authenticated %}
        {{ current_user.username }}
    {% else %}
        Stranger
    {% endif %}
    </h1>
</div>
<div>
    {% if current_user.can(Permission.WRITE_ARTICLES) %}
    {{ wtf.quick_form(form) }}
    {% endif %}
</div>
<br>
<div class='post-tabs'>
    {% include 'main/_posts.html' %}
</div>
<div>
    {{ macros.pagination_widget(pagination, 'main.index') }}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

app/templates/main/moderate.html
{% extends 'base.html' %}
{% import 'main/_macros.html' as macros %}

{% block title %}Flasky - Comment Moderation{% endblock %}

{% block page_content %}
<div class='page-header'>
    <h1>Comment Moderation</h1>
</div>
{% set moderate=True %}
{% include 'main/_comments.html' %}
{% if pagination %}
<div class='pagination'>
    {{ macros.pagination_widget(pagination, 'main.moderate') }}
</div>
{% endif %}
{% endblock %}

app/templates/main/post.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% import 'main/_macros.html' as macros %}

{% block title %}Flasky - Post{% endblock %}

{% block page_content %}
{% include 'main/_posts.html' %}
{% for post in posts %}
<h4 id='comments'>Comments({{ post.comments.count() }})</h4>
{% endfor %}
{% if current_user.can(Permission.COMMENT) %}
<div class='comment-form'>
    {{ wtf.quick_form(form) }}
</div>
{% endif %}
{% include 'main/_comments.html' %}
{% if pagination %}
<div class='pagination'>
    {{ macros.pagination_widget(pagination, 'main.post', fragment='#comments', id=posts[0].id) }}
</div>
{% endif %}
{% endblock %}

app/templates/main/user.html
{% extends 'base.html' %}
{% import 'main/_macros.html' as macros %}

{% block title %}Flask - {{ user.username }}'s space{% endblock %}

{% block page_content %}
<div class='page-header'>
    <div class='row'>
        <div class='col-md-3'>
            <img class='img-rounded profile-thumbnail' src='{{ user.gravatar(size=256) }}'>
        </div>
        <div class='col-md-9'>    
            <h1>{{ user.username }}
            {% if current_user == user %}
                <a class='btn btn-default' href="{{ url_for('auth.update_password') }}">Change my password</a>
                <a class='btn btn-default' href="{{ url_for('main.edit_profile') }}">Edit my profile</a>
            {% endif %}
            {% if current_user.is_administrator() %}
                <a class='btn btn-danger' href="{{ url_for('main.edit_profile_admin', id=user.id) }}">
                    Edit Profile [Admin]
                </a>
            {% endif %}
            </h1>
            <p>
            {% if user.name or user.location %}
                {% if user.name %}
                    {{ user.name }}
                {% endif %}
                {% if user.location %}
                    From<a href='http://maps.google.com/?q={{ user.location }}'>
                        {{ user.location }}
                    </a>
                {% endif %}
            {% endif %}
            </p>
            <p>
                {% if current_user.is_administrator() %}
                    <a href='mailto:{{ user.email }}'>{{ user.email }}</a>
                {% endif %}
            </p>
            <p>
                {% if user.about_me %}
                    {{ user.about_me }}
                {% endif %}
            </p>
            <p>
                Member since {{ moment(user.member_since).format('L') }}.
            </p>
            <p>
                Last seen {{ moment(user.last_seen).fromNow() }}.
            </p>
            <p>
                {{ user.posts.count() }} blog posts.
            </p>
            <p>
                {% if current_user.is_administrator() %}
                    <a href='mailto: {{ user.mail }}'>{{ user.mail }}</a>
                {% endif %}
            </p>
            <p>
            {% if current_user.can(Permission.FOLLOW) and user != current_user %}
                {% if not current_user.is_following(user) %}
                <a href="{{ url_for('main.follow', username=user.username) }}"
                    class='btn btn-primary'>Follow</a>
                {% else %}
                <a href="{{ url_for('main.unfollow', username=user.username) }}"
                    class='btn btn-default'>Unfollow</a>
                {% endif %}
            {% endif %}
            <a href="{{ url_for('main.followers', username=user.username) }}">
                Followers: <span class='badge'>{{ user.followers.count()-1 }}</span>
            </a>
            <a href="{{ url_for('main.followed_by', username=user.username) }}">
                Following: <span class='badge'>{{ user.followed.count()-1 }}</span>
            </a>
            {% if current_user.is_authenticated and user != current_user and
                user.is_following(current_user) %}
            | <span class='label label-default'>Following you</span>
            {% endif %}
        </div>
    </div>
    <hr>
    <h3>Posts by {{ user.username }}</h3>
    <div>
        {% include 'main/_posts.html' %}
    </div>
    <div>
        {{ macros.pagination_widget(pagination, 'main.user', username=user.username) }}
    </div>
</div>
{% endblock %}